#![cfg_attr(rustfmt, rustfmt_skip)]
// This file is autogenerated by build.rs, do not edit.

mod report_command;

pub fn get_all_commands() -> Vec<poise::Command<crate::Data, crate::types::Error>> {
    vec![
		report_command::report()]
}